"use strict";

window.DEVICE_CONTROLLERS = [
  { id:"uno-r4", name:"Arduino UNO R4 WiFi", maker:"Arduino", logic:5, supply:"USB-C or VIN 6–24 V", interfaces:["digital","pwm","analog","i2c","spi","uart","can"], pins:{digital:"D2",pwm:"D9",analog:"A0",i2c:"SDA / SCL",spi:"COPI / CIPO / SCK / CS",uart:"D0 RX / D1 TX"}, note:"RA4M1 GPIO operates at 5 V; ESP32-S3 connectivity is onboard.", source:"https://docs.arduino.cc/hardware/uno-r4-wifi/" },
  { id:"uno-r3", name:"Arduino UNO R3", maker:"Arduino", logic:5, supply:"USB-B or 7–12 V recommended", interfaces:["digital","pwm","analog","i2c","spi","uart"], pins:{digital:"D2",pwm:"D9",analog:"A0",i2c:"A4 SDA / A5 SCL",spi:"D11 COPI / D12 CIPO / D13 SCK / D10 CS",uart:"D0 RX / D1 TX"}, note:"Classic ATmega328P 5 V classroom board.", source:"https://docs.arduino.cc/hardware/uno-rev3/" },
  { id:"raspberry-pi-5", name:"Raspberry Pi 5", maker:"Raspberry Pi", logic:3.3, supply:"Official 5 V USB-C supply", interfaces:["digital","pwm","i2c","spi","uart"], pins:{digital:"GPIO17 · physical 11",pwm:"GPIO18 · physical 12",i2c:"GPIO2 SDA · GPIO3 SCL",spi:"GPIO10 MOSI · GPIO9 MISO · GPIO11 SCLK · GPIO8 CE0",uart:"GPIO14 TX · GPIO15 RX"}, noAdc:true, note:"All GPIO is 3.3 V. It has no general-purpose analog input; never apply 5 V to GPIO.", source:"https://www.raspberrypi.com/documentation/computers/raspberry-pi.html" },
  { id:"pico-2", name:"Raspberry Pi Pico 2", maker:"Raspberry Pi", logic:3.3, supply:"USB or VSYS 1.8–5.5 V", interfaces:["digital","pwm","analog","i2c","spi","uart"], pins:{digital:"GP2",pwm:"GP15",analog:"GP26 / ADC0",i2c:"GP4 SDA / GP5 SCL",spi:"GP19 MOSI / GP16 MISO / GP18 SCK / GP17 CS",uart:"GP0 TX / GP1 RX"}, note:"RP2350 microcontroller board; GPIO uses 3.3 V logic.", source:"https://www.raspberrypi.com/documentation/microcontrollers/pico-series.html" },
  { id:"teensy-41", name:"Teensy 4.1", maker:"PJRC", logic:3.3, supply:"USB or 5 V VIN", interfaces:["digital","pwm","analog","i2c","spi","uart","i2s"], pins:{digital:"Pin 2",pwm:"Pin 3",analog:"A0 / Pin 14",i2c:"Pin 18 SDA / Pin 19 SCL",spi:"Pin 11 MOSI / 12 MISO / 13 SCK / 10 CS",uart:"Pin 1 TX1 / Pin 0 RX1",i2s:"Audio-library pin set"}, note:"Pins are not 5 V tolerant; recommended GPIO output current is 4 mA.", source:"https://www.pjrc.com/store/teensy41.html" },
  { id:"esp32-devkitc", name:"Espressif ESP32-DevKitC V4", maker:"Espressif", logic:3.3, supply:"USB or 5 V header input", interfaces:["digital","pwm","analog","i2c","spi","uart","i2s"], pins:{digital:"GPIO18",pwm:"GPIO19",analog:"GPIO34 input-only",i2c:"GPIO21 SDA / GPIO22 SCL",spi:"GPIO23 MOSI / 19 MISO / 18 SCK / 5 CS",uart:"GPIO17 TX / GPIO16 RX",i2s:"Configurable GPIO"}, note:"Use the exact DevKitC variant and avoid boot-strapping pins until verified.", source:"https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32/esp32-devkitc/index.html" },
  { id:"microbit-v2", name:"BBC micro:bit V2", maker:"Micro:bit Educational Foundation", logic:3.3, supply:"USB or 3 V battery", interfaces:["digital","pwm","analog","i2c","spi","uart"], pins:{digital:"P0",pwm:"P1",analog:"P2",i2c:"P20 SDA / P19 SCL",spi:"P15 MOSI / P14 MISO / P13 SCK / P16 CS",uart:"Assign supported edge pins"}, note:"Use an edge-connector breakout for reliable breadboard wiring.", source:"https://tech.microbit.org/hardware/" }
];

window.DEVICE_LIBRARY = [
  {id:"led",category:"Basics",name:"5 mm LED",model:"Exact color required",logic:"passive",supply:"Use controller logic rail",interfaces:["digital","pwm"],driver:"resistor",note:"Add a calculated series resistor; observe anode/cathode polarity."},
  {id:"button",category:"Basics",name:"Momentary pushbutton",model:"4-pin tactile, normally open",logic:"passive",interfaces:["digital"],note:"Use INPUT_PULLUP or a verified external pull resistor."},
  {id:"pot",category:"Basics",name:"10 kΩ potentiometer",model:"Linear taper",logic:"passive",interfaces:["analog"],note:"Outer lugs to logic rail and GND; wiper to analog input."},
  {id:"ldr",category:"Sensors",name:"Photoresistor divider",model:"LDR + fixed resistor",logic:"analog",interfaces:["analog"],note:"Build a voltage divider and keep output within the ADC range."},
  {id:"tmp36",category:"Sensors",name:"TMP36 temperature sensor",model:"TMP36GT9Z TO-92",logic:"analog",supply:"2.7–5.5 V",interfaces:["analog"],note:"Verify flat-face pin order before wiring.",source:"https://www.analog.com/en/products/tmp36.html"},
  {id:"hcsr04",category:"Sensors",name:"HC-SR04 ultrasonic module",model:"HC-SR04 4-pin",logic:5,supply:"5 V",interfaces:["digital"],levelShift:true,note:"Echo output is 5 V; divide or shift it before any 3.3 V GPIO."},
  {id:"dht22",category:"Sensors",name:"DHT22 humidity sensor",model:"AM2302 / DHT22",logic:3.3,supply:"3.3–5.5 V",interfaces:["digital"],note:"Use the required data pull-up and confirm bare sensor versus module pin order."},
  {id:"mpu6050",category:"Sensors",name:"MPU-6050 IMU breakout",model:"Exact breakout required",logic:3.3,supply:"Module-dependent",interfaces:["i2c"],address:"0x68/0x69",verify:true,note:"Regulator and pull-up voltages vary by breakout; verify the exact board."},
  {id:"ssd1306",category:"Displays",name:"SSD1306 OLED module",model:"128×64 I²C breakout",logic:3.3,supply:"Module-dependent",interfaces:["i2c"],address:"0x3C/0x3D",verify:true,note:"Confirm four-pin order and regulator/level-shifter population."},
  {id:"ws2812",category:"Displays",name:"WS2812B addressable LEDs",model:"5 V strip or ring",logic:5,supply:"5 V external",interfaces:["digital"],levelShift:true,externalPower:true,note:"Add bulk capacitance, data resistor, common ground, and a 3.3-to-5 V level shifter when needed."},
  {id:"buzzer",category:"Sound",name:"Passive piezo buzzer",model:"High-impedance piezo",logic:"passive",interfaces:["pwm"],note:"Use PWM/tone output; confirm it is passive rather than an active buzzer."},
  {id:"i2s-mic",category:"Sound",name:"I²S MEMS microphone",model:"Exact 3.3 V breakout required",logic:3.3,supply:"3.3 V",interfaces:["i2s"],verify:true,note:"Pin names and channel-select behavior vary; exact breakout is required."},
  {id:"sg90",category:"Actuators",name:"SG90-class micro servo",model:"Exact servo required",logic:"either",supply:"External regulated 5 V",interfaces:["pwm"],externalPower:true,note:"Do not power the servo from a GPIO pin; join controller and servo-supply grounds."},
  {id:"dc-motor",category:"Actuators",name:"Brushed DC motor",model:"Voltage and stall current required",logic:"load",interfaces:["pwm"],driver:"hbridge",externalPower:true,verify:true,note:"Requires a motor driver sized for stall current and inductive protection."},
  {id:"stepper28",category:"Actuators",name:"28BYJ-48 stepper motor",model:"5 V version + ULN2003 board",logic:5,supply:"External 5 V",interfaces:["digital"],driver:"uln2003",externalPower:true,note:"Power the motor separately and share ground with the controller."},
  {id:"relay",category:"Actuators",name:"Relay module",model:"Exact module required",logic:"unknown",supply:"Module-dependent",interfaces:["digital"],externalPower:true,verify:true,note:"Input polarity, trigger voltage, isolation, and flyback protection vary. Never use student breadboards for mains."},
  {id:"mcp3008",category:"Interface ICs",name:"MCP3008 ADC",model:"MCP3008-I/P PDIP-16",logic:"either",supply:"2.7–5.5 V",interfaces:["spi"],addsAdc:true,note:"Power at the controller logic voltage; provides eight 10-bit analog inputs.",source:"https://www.microchip.com/en-us/product/MCP3008"},
  {id:"sn74hc595",category:"Interface ICs",name:"SN74HC595 shift register",model:"SN74HC595N PDIP-16",logic:"either",supply:"2–6 V",interfaces:["spi"],note:"Power at the controller logic voltage and add local bypass capacitance.",source:"https://www.ti.com/lit/ds/symlink/sn74hc595.pdf"},
  {id:"l293d",category:"Driver ICs",name:"L293D motor driver",model:"L293DNE PDIP-16",logic:5,supply:"5 V logic + 4.5–36 V motor",interfaces:["digital","pwm"],driverFor:"hbridge",externalPower:true,note:"Up to 600 mA per channel; check motor stall current and heat.",source:"https://www.ti.com/lit/ds/symlink/l293d.pdf"},
  {id:"uln2003",category:"Driver ICs",name:"ULN2003A driver array",model:"ULN2003AN PDIP-16",logic:5,supply:"Load supply up to device rating",interfaces:["digital"],driverFor:"uln2003",externalPower:true,note:"Seven low-side Darlington channels with common flyback-diode connection.",source:"https://www.ti.com/lit/ds/symlink/uln2003a.pdf"},
  {id:"pca9685",category:"Interface Modules",name:"PCA9685 PWM/servo board",model:"Exact breakout required",logic:"either",supply:"Logic + external servo rail",interfaces:["i2c"],address:"0x40 default",externalPower:true,verify:true,note:"Do not bridge servo power into controller logic power; verify address jumpers."},
  {id:"level-shifter",category:"Interface Modules",name:"Bidirectional logic-level shifter",model:"Exact channel count and topology required",logic:"either",supply:"Both logic rails",interfaces:["digital","i2c","spi","uart"],note:"MOSFET boards suit open-drain buses; push-pull/high-speed signals may require a different translator."},
  {id:"ne555p",category:"Analog ICs",name:"NE555P timer",model:"Texas Instruments NE555P PDIP-8",logic:5,supply:"4.5–16 V",interfaces:["analog"],note:"Standalone timer; use the verified astable/monostable preset rather than direct GPIO wiring.",source:"https://www.ti.com/lit/ds/symlink/ne555.pdf"},
  {id:"tl072cp",category:"Analog ICs",name:"TL072CP dual op-amp",model:"Texas Instruments TL072CP PDIP-8",logic:"analog",supply:"Circuit-dependent",interfaces:["analog"],note:"Not rail-to-rail; use the verified biased audio preset for single-supply operation.",source:"https://www.ti.com/product/TL072/part-details/TL072CP"},
  {id:"cd40106be",category:"Logic ICs",name:"CD40106BE Schmitt inverter",model:"Texas Instruments CD40106BE PDIP-14",logic:"either",supply:"3–18 V",interfaces:["digital","analog"],note:"Tie every unused input to a defined logic level.",source:"https://www.ti.com/lit/ds/symlink/cd40106b.pdf"}
];
